GET http://localhost:3333/wards?query=
Content-Type: application/json

###
POST http://localhost:3333/wards
Content-Type: application/json

{
  "name": "Itaquaquecetuba",
  "stake": "Itaquaquecetuba"
}